### ISSUE TITLE
Drawimage crash

### ISSUE THREAD

**Issue by h-m-m-m** [NRGJobro/Horion-Open-SRC#2]
**Describe the bug**
doing drawutils::drawimage() crashes the game

**To Reproduce**
1. Add DrawUtils::DrawImage() to your code
2. build&inject
3. crashes

**Expected behavior**
draw the image

**Additional context**
the crash is in drawutils::drawimage but flushimages() crashes the game, it might be because flushimageaddr is 0

error: An invalid parameter was passed to a function that considers invalid parameters fatal.

**Comment by shinxe** [comment]
Would you tell me how to use DrawImage()?

**Comment by h-m-m-m** [comment]
> Would you tell me how to use DrawImage()?

DrawUtils::drawImage(path, vec2_t(100,100), vec2_t(0,0), vec2_t(0,0));

**Comment by shinxe** [comment]
What kind of image file format do you use?

**Comment by h-m-m-m** [comment]
> What kind of image file format do you use?

.png

**Comment by Intoprelised** [comment]
Ok so our drawimage isint currently working but we are working on a fix, if im correct the code for it works on 1.18.2

**Comment by Intoprelised** [comment]
It is our addr

**Comment by NRGJobro** [comment]
This is the most professional bug opening I have seen so far. We will work on fixing the draw image very soon. We are currently working on some other projects. Thank you for reporting this and we will work on it soon

**Comment by NRGJobro** [comment]
![0C01BD3E-3AB2-465F-94B5-3ECF3B508AF5](https://user-images.githubusercontent.com/85864573/158021102-72a03a1f-b036-4467-9d77-e7c2e3f0faf1.png)

We had it working last update but we just have to fix the address

**Comment by NRGJobro** [comment]
We also are not currently planning on releasing it to the public because then it wouldn’t be special to have a draw image. Maybe if more people find how to fix it then we may release it in here in the future. Thank you for this pull request and I hope to see more soon!

**Comment by Intoprelised** [comment]
@h-m-m-m I do have to say, this is the most profesional bug report ive seen, very nice

**Comment by Turkeii** [comment]
ya know that shinxe cunt is just gonna resell your code

**Comment by Intoprelised** [comment]
> ya know that shinxe cunt is just gonna resell your code

yeah

**Comment by Intoprelised** [comment]
Thanks for reporting this but we wont be releasing this to the public once we have a fix.
