### ISSUE TITLE
the license doesnt count

### ISSUE THREAD

**Issue by Loko415** [NRGJobro/Horion-Open-SRC#24]
update to 1.19. also your license doesnt protect your project because its using another licensed project. Sooo i or packet can resell skid this fork of horion.

**Comment by xRodzMC** [comment]
Lmao

**Comment by xqwtxon** [comment]
Alr buddy

**Comment by RealPacket** [comment]
LOL

**Comment by NRGJobro** [comment]
> 

I hope ur joking lmfao. First off, U cant sell it because its horions license. This is a fork of horion but updated. Also, learn to update your self u average skid

**Comment by xRodzMC** [comment]
Lamoooo
