### ISSUE TITLE
Please teach me

### ISSUE THREAD

**Issue by cngege** [NRGJobro/Horion-Open-SRC#40]
These feature codes contain the address of the dummy table
How can I find these eigencodes?
![图片](https://user-images.githubusercontent.com/28597788/184845814-499155b5-d862-4265-80b6-617db85f2b27.png)

**Comment by Intoprelised** [comment]
dummy is a strong word we use "autistic table"

**Comment by cngege** [comment]
Thanks, but how should I use Cheat Engine to find them in memory?

**Comment by cngege** [comment]
> dummy is a strong word we use "autistic table"

Thanks, but how should I use Cheat Engine to find them in memory?

**Comment by xRodzMC** [comment]
Check yaami tutorial but hes a skidder :((

**Comment by cngege** [comment]
> Check yaami tutorial but hes a skidder :((

Thank you, can you give me a relevant URL?

**Comment by xRodzMC** [comment]
> > Check yaami tutorial but hes a skidder :((
> 
> Thank you, can you give me a relevant URL?

https://youtube.com/channel/UCERJdZ47m6o5CDMDh4ZXL4w

**Comment by cngege** [comment]
> > > Check yaami tutorial but hes a skidder :((
> > 
> > 
> > Thank you, can you give me a relevant URL?
> 
> https://youtube.com/channel/UCERJdZ47m6o5CDMDh4ZXL4w

Thank you very much
