### ISSUE TITLE
Question: Crashing on latest version

### ISSUE THREAD

**Issue by xRodzMC** [NRGJobro/Horion-Open-SRC#44]
Why its crashing on latest version? Is this checking mc version? What line is it or what library uses minecraft protocol version to measure compability with this hack?

I'd like to update this latest version, if someone teach me this source on protocol library. Since i have project tools such as finding signatures etc....

What does line containing minecraft version checks or library that checks the minecraft version?

**Comment by NRGJobro** [comment]
It does not use any librarys to determine compatability. You would need to update the signatures, vtables, offsets, and vtable numebers in hooks, and some other things. There is nothing to check the MC version in this
