### ISSUE TITLE
keyboardinput malfunction （2023.1.25）

### ISSUE THREAD

**Issue by LillacUltimate324** [NRGJobro/Horion-Open-SRC#45]
（2023.1.25）produce
when i press “insert” to open clickgui
the keyboard input of the game will not work
include W A S D , ESC
I cant move, suspend，or quit

**Comment by Intoprelised** [comment]
There is currently a problem with entity which will be fixed shortly but I have tested and I do not have the same issue as you. What version are you on?

**Comment by LillacUltimate324** [comment]
> 

On Minecraft 1.18.12

**Comment by NRGJobro** [comment]
Im not sure what is causing whatever is happening for you so im going to close it for now.
