### ISSUE TITLE
Build errors and crashs

### ISSUE THREAD

**Issue by hydraontopp** [NRGJobro/Horion-Open-SRC#5]
I had a error with the image load in MinecraftUIRenderContext, how could i fix this?

**Comment by NRGJobro** [comment]
I will get someone to look at this error later. Thx for the comment

**Comment by hydraontopp** [comment]
> I will get someone to look at this error later. Thx for the comment

np

**Comment by Intoprelised** [comment]
Build errors have been resolved we will check crashes now
