### ISSUE TITLE
Why only support 1.18, but not the latest version?

### ISSUE THREAD

**Issue by cngege** [NRGJobro/Horion-Open-SRC#66]
**Is your feature request related to a problem? Please describe.**
The title is very concise

**Describe the solution you'd like**
The title is very concise

**Describe alternatives you've considered**
The title is very concise

**Additional context**
The title is very concise

**Comment by Intoprelised** [comment]
We have decided not to update this publicly to 1.20.10 but we have privately, [Borion Org](https://github.com/Borion-Updated/)

**Comment by cngege** [comment]
Well, but anyway, the code you released has benefited me a lot, and also taught me a lot of technology, thank you

**Comment by Intoprelised** [comment]
Np
